
export const CHANGE_MESSAGE= 'CHANGE_MESSAGE'


//CART
export const DELETE_TO_CART='DELETE_TO_CART'
export const UPDATE_TO_CART ='UPDATE_TO_CART'
export const BUY_TO_CART ='BUY_TO_CART'
export const ADD_TO_CART= 'ADD_TO_CART'
export const FETCH_TO_CART= 'FETCH_TO_CART'
//Product
export const FETCH_PRODUCTS= 'FETCH_PRODUCTS'
export const ADD_TO_PRODUCT= 'ADD_TO_PRODUCT'
export const DELETE_TO_PRODUCT='DELETE_TO_PRODUCT'
export const UPDATE_TO_PRODUCT ='UPDATE_TO_PRODUCT'
export const PRODUCT_TYPE_LIST ='PRODUCT_TYPE_LIST'
export const PRODUCT_FIND_BY_KEY_WORD= 'PRODUCT_FIND_BY_KEY_WORD'
//PRODUCTSIZE
export const FETCH_PRODUCTS_SIZE= 'FETCH_PRODUCTS_SIZE'
export const ADD_TO_PRODUCT_SIZE= 'ADD_TO_PRODUCT_SIZE'
export const DELETE_TO_PRODUCT_SIZE='DELETE_TO_PRODUCT_SIZE'
export const UPDATE_TO_PRODUCT_SIZE ='UPDATE_TO_PRODUCT_SIZE'
export const PRODUCT_SIZE_LIST ='PRODUCT_SIZE_LIST'
//PRODUCTSTATUS
export const FETCH_PRODUCTS_STATUS= 'FETCH_PRODUCTS_STATUS'
export const ADD_TO_PRODUCT_STATUS= 'ADD_TO_PRODUCT_STATUS'
export const DELETE_TO_PRODUCT_STATUS='DELETE_TO_PRODUCT_STATUS'
export const UPDATE_TO_PRODUCT_STATUS ='UPDATE_TO_PRODUCT_STATUS'
export const PRODUCT_STATUS_LIST ='PRODUCT_STATUS_LIST'
//PRODUCTTYPE
export const FETCH_PRODUCTS_TYPE= 'FETCH_PRODUCTS_TYPE'
export const ADD_TO_PRODUCT_TYPE= 'ADD_TO_PRODUCT_TYPE'
export const DELETE_TO_PRODUCT_TYPE='DELETE_TO_PRODUCT_TYPE'
export const UPDATE_TO_PRODUCT_TYPE ='UPDATE_TO_PRODUCT_TYPE'
// export const PRODUCT_TYPE_LIST ='PRODUCT_TYPE_LIST'

//SALEOFF
export const FETCH_SALE_OFF= 'FETCH_SALE_OFF'
export const ADD_TO_SALE_OFF= 'ADD_TO_SALE_OFF'
export const DELETE_TO_SALE_OFF='DELETE_TO_SALE_OFF'
export const UPDATE_TO_SALE_OFF ='UPDATE_TO_SALE_OFF'

//BILLDETAIL
export const FETCH_BILL_DETAIL= 'FETCH_BILL_DETAIL'
export const ADD_TO_BILL_DETAIL= 'ADD_TO_BILL_DETAIL'
export const DELETE_TO_BILL_DETAIL='DELETE_TO_BILL_DETAIL'
export const UPDATE_TO_BILL_DETAIL ='UPDATE_TO_BILL_DETAIL'

//SALEOFF
export const FETCH_USER= 'FETCH_USER'
export const ADD_TO_USER= 'ADD_TO_USER'
export const DELETE_TO_USER='DELETE_TO_USER'
export const UPDATE_TO_USER ='UPDATE_TO_USER'
